CREATE TABLE USER
(
    UserID int UNIQUE NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    FAVORITE_RESTAURANT INT,
    PRIMARY KEY (UserID),
    FOREIGN KEY (FAVORITE_RESTAURANT) REFERENCES RESTAURANT (RID)
);

CREATE TABLE CONTACT
(
    EMAIL VARCHAR(30) NOT NULL,
    PhoneNumber INT NOT NULL,
    UID INT UNIQUE NOT NULL,
    FOREIGN KEY (UID) REFERENCES USER (UserID),
    PRIMARY KEY (UID)
);

CREATE TABLE CITY
(
    NAME VARCHAR(30) NOT NULL,
    STATE VARCHAR(30) NOT NULL,
    PRIMARY KEY (NAME, STATE)
);

CREATE TABLE REVIEW(
    RATING INT NOT NULL,
    UID INT UNIQUE NOT NULL,
    RID INT UNIQUE NOT NULL, 
    FOREIGN KEY(UID) REFERENCES USER(UserID),
    FOREIGN KEY(RID) REFERENCES RESTUARANT(RID)
);

CREATE TABLE RESTAURANT(
    RID INT UNIQUE NOT NULL,
    ADDRESS VARCHAR(50) NOT NULL,
    CITY VARCHAR(30) NOT NULL,
    CUISINE VARCHAR(20) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (RID),
    FOREIGN KEY (CITY) REFERENCES CITY(NAME)
);

CREATE TABLE HOURS(
    START_TIME VARCHAR (15),
    END_TIME VARCHAR (15),
    TIME_NAME VARCHAR(20),
    REST_ID INT UNIQUE NOT NULL,
    PRIMARY KEY (TIME_NAME),
    FOREIGN KEY (REST_ID) REFERENCES RESTAURANT(RID)
);

CREATE TABLE RCONTACT(
EMAIL VARCHAR (50) UNIQUE NOT NULL,
PHONE_NUMBER CHAR(10) UNIQUE NOT NULL,
REST_ID INT UNIQUE NOT NULL,
PRIMARY KEY (EMAIL, PHONE_NUMBER),
FOREIGN KEY (REST_ID) REFERENCES RESTAURANT(RID)
);

CREATE TABLE MENU(
    LANGUAGES VARCHAR(30),
    R_ID INT UNIQuE NOT NULL,
    PRIMARY KEY (LANGUAGES),
    FOREIGN KEY (R_ID) REFERENCES RESTAURANT(RID)
);

CREATE TABLE FOOD_ENTIRES(
PRICES VARCHAR(15),
NAME VARCHAR(60),
R_MENUID INT UNIQuE NOT NULL,
PRIMARY KEY (NAME),
FOREIGN KEY (R_MENUID) REFERENCES MENU(R_ID)
);
